#Prefix to show metrics in AppDynamics.
#Please find your Component ID by following the metric path section of this document - https://docs.appdynamics.com/display/PRO42/Build+a+Monitoring+Extension+Using+Java
metricPrefix: "Server|Component:<COMPONENT_ID>|Custom Metrics|Log Monitor"


#Generic Metric Prefix, publishes metrics to all tiers within associated application (NOT RECOMMENDED)
#metricPrefix: "Custom Metrics|Log Monitor"

logs:
  - displayName: "Machine Agent Log"
    logDirectory: "/Users/aditya.jagtiani/appdynamics/machineagent-4.1.8.12/logs/"
    logName: "machine-agent.log"
    searchStrings:
        #displayName Should be unique across the patterns including the case.
       - displayName: "Debug In Caps"
         pattern: "DEBUG"
         matchExactString: false
         caseSensitive: true
         printMatchedString: false
       - displayName: "Info"
         pattern: "Info"
         matchExactString: false
         caseSensitive: false
         printMatchedString: true

#Replaces characters in metric name with the specified characters.
# "replace" takes any regular expression
# "replaceWith" takes the string to replace the matched characters
metricCharacterReplacer:
    - replace: ":"
      replaceWith: ";"
    - replace: "\\|"
      replaceWith: "#"
# Number of concurrent threads
noOfThreads: 3
