#prefix used to show metrics in all tiers (NOT RECOMMENDED)
#metricPrefix: "Custom Metrics|LogMonitor|"

# metric prefix to show metrics in one tier (HIGHLY RECOMMENDED)
# Please follow the Metric Path section of https://docs.appdynamics.com/display/PRO42/Build+a+Monitoring+Extension+Using+Java for instructions on retrieving the tier ID

metricPrefix: "Server|Component:<TIER_ID>|Custom Metrics|Log Monitor|"

logs:
  - displayName: "Machine Agent Log"
    logDirectory: "/Users/aditya.jagtiani/appdynamics/machineagent-4.1.8.12/logs/test"
    logName: "error.log"
    searchStrings:
       - displayName: "Error in uppercase"
         pattern: "ERROR"
         matchExactString: false
         caseSensitive: false
         printMatchedString: false
        #displayName Should be unique across the patterns including the case.
       - displayName: "Debug In lowercase"
         pattern: "debug"
         matchExactString: true
         caseSensitive: false
         printMatchedString: false
       - displayName: "Trace in lowercase"
         pattern: "trace"
         matchExactString: false
         caseSensitive: false
         printMatchedString: false

#Replaces characters in metric name with the specified characters.
# "replace" takes any regular expression
# "replaceWith" takes the string to replace the matched characters
metricCharacterReplacer:
    - replace: ":"
      replaceWith: ";"
    - replace: "\\|"
      replaceWith: "#"

# Number of concurrent threads
noOfThreads: 3

#Thread timeout in seconds
threadTimeOut: 60
