logs:
  - displayName: "Machine Agent Log"
    logDirectory: "/Users/aditya.jagtiani/appdynamics/machineagent-4.1.8.12/logs/"
    logName: "machine-agent.log"
    searchStrings:
       - displayName: "Info in lowercase"
         pattern: "info"
         matchExactString: false
         caseSensitive: false
         printMatchedString: true
        #displayName Should be unique across the patterns including the case.
       - displayName: "Debug In Caps"
         pattern: "debug"
         matchExactString: true
         caseSensitive: false
         printMatchedString: false
       - displayName: "Trace in any case"
         pattern: "trace"
         matchExactString: false
         caseSensitive: false
         printMatchedString: false

#Replaces characters in metric name with the specified characters.
# "replace" takes any regular expression
# "replaceWith" takes the string to replace the matched characters
metricCharacterReplacer:
    - replace: ":"
      replaceWith: ";"
    - replace: "\\|"
      replaceWith: "#"
# Number of concurrent threads
noOfThreads: 3

#prefix used to show up metrics in AppDynamics 
metricPrefix: "Custom Metrics|LogMonitor|"

controller:
    - url:
      username:
      password:
      accountName:

encryptionKey:
